"""Python reader for the canonical voice-control label contract.

llm/voice_contract.json is the ONE canonical source; host/Source/
VoiceContract.generated.h is its C++ consumer, generated by
tools/gen_voice_contract.py. This is a THIRD consumer, load-bearing rather
than generated: llm/generate.py's _validate_profile_metadata needs the exact
same accepted label set FaustEngine::extractVoiceControls matches against, so
a mis-cased or misspelled voice-contract label is caught as a validation
failure BEFORE a patch ships, instead of shipping a "successful" generation
whose keyboard the host silently refuses to enable -- the bug this module
exists to close. generate.py's _ui_labels() used to lowercase every UI label
before checking membership, which let e.g. hslider("Freq", ...) pass a check
that FaustEngine.cpp's exact-case match then silently rejected.

Deliberately reads the JSON directly rather than parsing the generated C++
header back out of it -- one JSON parse is simpler and more robust than a
second code generator, and it keeps this file agreeing with the C++ side by
construction (same source, not a fourth hand-synced copy).
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

CONTRACT_PATH = Path(__file__).with_name("voice_contract.json")


@lru_cache(maxsize=1)
def zone_labels() -> dict[str, frozenset[str]]:
    """{zone_name: {exact accepted labels}}, e.g. {"gate": frozenset({"gate"}),
    "freq": frozenset({"freq", "key"}), "gain": frozenset({"gain", "vel", "velocity"})}.

    Case-preserving -- FaustEngine::extractVoiceControls
    (host/Source/FaustEngine.cpp) matches Faust UI labels EXACTLY, and this
    must agree with it, not with the model's own idea of case.
    """
    raw = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    return {
        zone["zone"]: frozenset(label["label"] for label in zone["labels"])
        for zone in raw["zones"]
    }
