"""Prompt-grounding tests — the regression guard for the 2026-07-21 incident.

Both system prompts were found to teach Faust functions that do not exist
(`ef.ping_pong`, `ef.chorus`, `ef.flanger`), and two of the four few-shot examples
in the production prompt did not compile. That directly produced the two failure
modes recorded as "persistent model failures" for two months — the flanger prompt
failing with `undefined symbol : flanger_mono` (the model had the right function
name and the wrong namespace, because the prompt taught a fictitious one).

These tests make that class of defect impossible to reintroduce:

  1. every curated entry in tools/gen_stdlib_block.py resolves in the installed lib
  2. the checked-in generated block matches what the generator produces now
  3. every `ns.func` token anywhere in the prompt resolves — including the prose
     rules and the few-shot examples, which is where the fabrications actually were
  4. every few-shot example COMPILES

Skipped, not failed, when Faust is absent: the CI Python job deliberately installs
no compiler ("no API key or faust compiler required"). The build-host job does have
Faust and runs this file explicitly — see .github/workflows/test.yml.

A failure here after a Faust upgrade is a true positive, not flakiness: it means the
installed library no longer provides something the prompt promises the model.
"""
import shutil
import subprocess
import sys
import json
import tempfile
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
PROMPT_DIR = ROOT / "llm" / "prompts"
PROMPT_FILE = PROMPT_DIR / "system_prompt.txt"
FAUST_LIB_DIR = Path("/usr/share/faust")

# Which curated set each prompt's generated block is rendered from, and the
# minimum few-shot count that proves the extractor did not silently fail.
#
# ⚠️ A prompt missing from here FAILS test_every_prompt_has_a_profile rather than
# being skipped. That is the point: a new prompt file must be declared, not
# quietly excluded from the guards -- which is how llm/prompts/ ended up with one
# hard-coded path in every control in the first place.
PROFILE_FOR = {
    "system_prompt.txt":     ("effect",     4),
    "instrument_prompt.txt": ("instrument", 3),
    # Generated by tools/gen_presentation_prompt.py from system_prompt.txt +
    # llm/presentation_block.txt. Same profile as system_prompt.txt: its
    # stdlib block and few-shot examples are copied verbatim, only the
    # control-presentation block is added ahead of EXAMPLES:.
    "system_prompt_presentation.txt": ("effect", 4),
}


def _prompt_paths() -> list:
    return sorted(PROMPT_DIR.glob("*.txt"))

sys.path.insert(0, str(ROOT / "tools"))

needs_faust_libs = pytest.mark.skipif(
    not (FAUST_LIB_DIR / "stdfaust.lib").exists(),
    reason="Faust standard library not installed (CI Python job has no compiler)",
)
needs_faust_binary = pytest.mark.skipif(
    shutil.which("faust") is None,
    reason="faust compiler not on PATH (CI Python job has no compiler)",
)


@pytest.fixture(scope="module", params=_prompt_paths(), ids=lambda p: p.name)
def prompt_path(request):
    return request.param


@pytest.fixture(scope="module")
def prompt_text(prompt_path) -> str:
    return prompt_path.read_text()


@pytest.fixture(scope="module")
def prompt_profile(prompt_path) -> str:
    return PROFILE_FOR[prompt_path.name][0]


@pytest.fixture(scope="module")
def prompt_min_examples(prompt_path) -> int:
    return PROFILE_FOR[prompt_path.name][1]


def test_every_prompt_has_a_profile():
    """A prompt file nobody declared is a prompt nobody's guards are shaped for."""
    undeclared = [p.name for p in _prompt_paths() if p.name not in PROFILE_FOR]
    assert not undeclared, (
        f"{undeclared} exist in llm/prompts/ but are not in PROFILE_FOR, so the "
        "block-currency and few-shot checks do not know what to expect of them. "
        "Declare the profile rather than letting the file skip the guards."
    )


@needs_faust_libs
def test_every_curated_entry_resolves():
    """CURATED names a function that the installed stdfaust.lib does not export."""
    from gen_stdlib_block import resolve_all

    _, errors = resolve_all()
    assert not errors, (
        "Curated stdlib entries do not exist in the installed Faust library:\n  "
        + "\n  ".join(errors)
        + "\n\nEither a Faust upgrade renamed/removed them, or CURATED names "
          "something that never existed. Fix tools/gen_stdlib_block.py; do not "
          "weaken this check."
    )


@needs_faust_libs
def test_generated_block_is_current(prompt_text, prompt_profile, prompt_path):
    """The checked-in block drifted from what the generator produces."""
    from gen_stdlib_block import (BEGIN_MARKER, END_MARKER, PROFILES, render,
                                  resolve_all)

    groups, errors = resolve_all(PROFILES[prompt_profile])
    assert not errors, "resolve failed; see test_every_curated_entry_resolves"

    expected = render(groups)
    start = prompt_text.find(BEGIN_MARKER)
    end = prompt_text.find(END_MARKER)
    assert start != -1 and end != -1, (
        f"generated-block markers missing from {prompt_path.name}; "
        "the block must stay delimited so the generator can splice it"
    )
    actual = prompt_text[start:end + len(END_MARKER)]

    # The block's TEXT is faust-version-dependent; its CONTENT is not. faust
    # 2.70.3 (Ubuntu noble, what CI runs) declares ef.softclipQuadratic with no
    # argument list; 2.85.5 (Arch, the dev box) declares it as
    # ef.softclipQuadratic(x). Asserting byte-equality against a block rendered
    # from whatever faust happens to be installed therefore fails on any machine
    # that did not generate it -- which is exactly how CI run 29883328421 failed
    # on a prompt that was correct.
    #
    # So: byte-exact where it is meaningful (same version -- this is what catches
    # a hand-edit or a stale block), and the version-independent property
    # everywhere else.
    from gen_stdlib_block import block_faust_version, entry_names, faust_version

    recorded = block_faust_version(actual)
    running = faust_version()

    if recorded != "unknown" and recorded == running:
        assert actual == expected, (
            "The generated stdlib block in the system prompt is stale or was "
            "hand-edited. Regenerate it:\n"
            "    python tools/gen_stdlib_block.py --write"
        )
    else:
        missing = entry_names(expected) - entry_names(actual)
        extra = entry_names(actual) - entry_names(expected)
        assert not missing and not extra, (
            f"The stdlib block teaches a different SET of functions than this "
            f"machine's faust produces (block generated with {recorded}, running "
            f"{running}).\n"
            f"  missing from the prompt: {sorted(missing)}\n"
            f"  present but unresolvable: {sorted(extra)}\n"
            "A pure formatting difference between faust releases is expected and "
            "is deliberately not asserted here; a difference in which functions "
            "are taught is not. Regenerate with:\n"
            "    python tools/gen_stdlib_block.py --write"
        )


@needs_faust_libs
def test_no_fabricated_stdlib_references(prompt_text):
    """A `ns.func` reference anywhere in the prompt names a nonexistent function."""
    from gen_stdlib_block import verify_prompt_references

    problems = verify_prompt_references(prompt_text)
    assert not problems, (
        "The system prompt references Faust functions that do not exist:\n  "
        + "\n  ".join(problems)
        + "\n\nThis is the exact defect found 2026-07-21 (ef.ping_pong, ef.chorus, "
          "ef.flanger). A few-shot example is the strongest signal in the prompt: "
          "teaching a fabricated name licenses the model to invent more."
    )


@needs_faust_libs
def test_prompt_has_few_shot_examples(prompt_text, prompt_min_examples):
    """Guards the extractor itself — a silent parse failure would make the
    compile test below vacuously pass."""
    from gen_stdlib_block import iter_prompt_examples

    examples = iter_prompt_examples(prompt_text)
    assert len(examples) >= prompt_min_examples, (
        f"expected at least {prompt_min_examples} few-shot examples, extracted "
        f"{len(examples)}. If the prompt's USER:/FAUST: layout changed, update "
        "iter_prompt_examples()."
    )
    for idx, code in examples:
        assert 'import("stdfaust.lib")' in code, (
            f"example {idx} does not start with the required import — either the "
            "example is wrong or the extractor mis-sliced it"
        )


@needs_faust_binary
@needs_faust_libs
def test_every_few_shot_example_compiles(prompt_text):
    """A few-shot example that does not compile teaches the model to write
    code that does not compile. Two of four used to fail this."""
    from gen_stdlib_block import iter_prompt_examples

    failures = []
    for idx, code in iter_prompt_examples(prompt_text):
        with tempfile.NamedTemporaryFile("w", suffix=".dsp", delete=False) as fh:
            fh.write(code)
            tmp = fh.name
        try:
            result = subprocess.run(
                ["faust", "-lang", "cpp", tmp, "-o", "/dev/null"],
                capture_output=True, text=True, timeout=30,
            )
            if result.returncode != 0:
                first_line = code.splitlines()[1] if len(code.splitlines()) > 1 else ""
                failures.append(
                    f"example {idx} ({first_line[:40]}...): {result.stderr.strip()[:200]}"
                )
        finally:
            Path(tmp).unlink(missing_ok=True)

    assert not failures, "Few-shot examples do not compile:\n  " + "\n  ".join(failures)


@needs_faust_binary
@needs_faust_libs
def test_instrument_few_shots_declare_the_voice_contract(prompt_text, prompt_profile):
    """An instrument few-shot that does not satisfy the voice contract teaches the
    model to write a synth that cannot be played.

    ⚠️ COMPILING IS NOT ENOUGH, and this test exists because that gap bit during
    authoring. The percussive example declared `freq` and never used it; Faust
    ELIMINATES a control nothing reads, so the compiled UI had only gain and gate.
    It compiled cleanly, it was 0-in/1-out, and `FaustEngine::isInstrument()` would
    have returned false for it forever -- a silent, permanently mute patch, taught
    to the model as the way to write percussion.

    So this asserts the property the host actually keys on -- the three controls
    present in the COMPILED UI (Faust's own predicate, MidiUI.h:115-132) -- rather
    than their presence in the source text, which is what misled in the first place.
    """
    if prompt_profile != "instrument":
        pytest.skip("voice contract applies to the instrument prompt only")

    from gen_stdlib_block import iter_prompt_examples

    failures = []
    for idx, code in iter_prompt_examples(prompt_text):
        with tempfile.TemporaryDirectory() as d:
            dsp = Path(d) / "ex.dsp"
            dsp.write_text(code)
            result = subprocess.run(
                ["faust", "-json", str(dsp), "-o", "/dev/null"],
                capture_output=True, text=True, timeout=30, cwd=d,
            )
            if result.returncode != 0:
                failures.append(f"example {idx}: did not compile")
                continue

            meta = json.loads((Path(d) / "ex.dsp.json").read_text())

            labels = []

            def walk(items):
                for item in items:
                    if "items" in item:
                        walk(item["items"])
                    elif "label" in item:
                        labels.append(item["label"])

            walk(meta.get("ui", []))

            missing = [n for n in ("freq", "gain", "gate") if n not in labels]
            if missing:
                failures.append(
                    f"example {idx}: compiled UI is missing {missing} -- declared "
                    f"but unused controls are deleted by Faust. Present: {labels}"
                )
            if meta["inputs"] != 0:
                failures.append(
                    f"example {idx}: has {meta['inputs']} audio inputs; an "
                    "instrument generates sound and must have 0"
                )

    assert not failures, (
        "Instrument few-shots break the voice contract:\n  " + "\n  ".join(failures)
    )
