// Generated by tools/gen_generation_profiles.py. Do not hand-edit.
#pragma once
#include <juce_core/juce_core.h>
#include <array>

namespace GenerationProfiles
{
struct Profile { const char* id; const char* displayName; const char* kind; };
inline constexpr std::array<Profile, 5> all {{
    { "effect", "Effect", "effect" },
    { "granular_effect", "Granular Effect", "effect" },
    { "synth", "Synth", "instrument" },
    { "drum_synth", "Drum Synth", "instrument" },
    { "generator", "Generator / Drone", "instrument" },
}};

inline constexpr std::array<const char*, 0> terms_effect {{}};
inline constexpr std::array<const char*, 5> terms_granular_effect {{"granular", "granulate", "granulator", "grain cloud", "grains"}};
inline constexpr std::array<const char*, 0> terms_synth {{}};
inline constexpr std::array<const char*, 10> terms_drum_synth {{"drum", "kick", "snare", "hi-hat", "hihat", "tom", "clap", "cymbal", "percussion", "percussive"}};
inline constexpr std::array<const char*, 7> terms_generator {{"drone", "generator", "generative", "self-playing", "self playing", "ambient texture", "soundscape"}};
inline constexpr std::array<const char*, 1> terms_synth_override {{"synth"}};

inline const Profile* find(juce::String id)
{
    id = id.trim().toLowerCase();
    for (const auto& profile : all)
        if (id == profile.id) return &profile;
    return nullptr;
}

template <size_t N>
inline bool matchesAny(const juce::String& text, const std::array<const char*, N>& terms)
{
    for (const auto* term : terms)
        if (text.contains(term)) return true;
    return false;
}

inline const Profile& resolveAuto(const juce::String& prompt, bool synthHost)
{
    const auto text = prompt.toLowerCase();
    if (synthHost)
    {
        if (matchesAny(text, terms_drum_synth)) return *find("drum_synth");
        if (matchesAny(text, terms_generator) && ! matchesAny(text, terms_synth_override)) return *find("generator");
        return *find("synth");
    }
    if (matchesAny(text, terms_granular_effect)) return *find("granular_effect");
    return *find("effect");
}
} // namespace GenerationProfiles
