#pragma once
// BEGIN GENERATED VOICE CONTRACT
// Generated by tools/gen_voice_contract.py from llm/voice_contract.json.
// Do not hand-edit: run the script. This is the canonical source
// FaustEngine::extractVoiceControls (FaustEngine.cpp) matches Faust
// parameter labels against -- the only place in C++ the accepted
// spellings are listed.

namespace pf::VoiceContract
{
// A label FaustEngine recognises for a voice zone, and whether it carries
// RAW MIDI units (key: the note number; vel/velocity: 0-127) rather than
// the zone's default units (freq: Hz; gain: 0-1) -- see FaustEngine::noteOn
// for the conversion this flag selects.
struct Label { const char* name; bool rawUnits; };

// Match order matters in every list below: first entry wins when a patch
// declares more than one spelling for the same zone
// (extractVoiceControls's "first match wins per role").

inline constexpr Label kGateLabels[] = {
    { "gate", false },
};
inline constexpr Label kFreqLabels[] = {
    { "freq", false },
    { "key", true },
};
inline constexpr Label kGainLabels[] = {
    { "gain", false },
    { "vel", true },
    { "velocity", true },
};
} // namespace pf::VoiceContract
// END GENERATED VOICE CONTRACT
