#!/usr/bin/env python3
"""Generate the C++ family catalog from llm/generation_profiles.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "llm" / "generation_profiles.json"
TARGET = ROOT / "host" / "Source" / "GenerationProfiles.generated.h"


def _cpp(value: str) -> str:
    return json.dumps(value)


def render() -> str:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    profiles = data["profiles"]
    lines = [
        "// Generated by tools/gen_generation_profiles.py. Do not hand-edit.",
        "#pragma once",
        "#include <juce_core/juce_core.h>",
        "#include <array>",
        "",
        "namespace GenerationProfiles",
        "{",
        "struct Profile { const char* id; const char* displayName; const char* kind; };",
        f"inline constexpr std::array<Profile, {len(profiles)}> all {{{{",
    ]
    for profile in profiles:
        lines.append(
            f"    {{ {_cpp(profile['id'])}, {_cpp(profile['display_name'])}, {_cpp(profile['kind'])} }},"
        )
    lines.extend(["}};", ""])
    for profile in profiles:
        terms = profile.get("auto_terms", [])
        lines.append(
            f"inline constexpr std::array<const char*, {len(terms)}> terms_{profile['id']} {{{{"
            + ", ".join(_cpp(term) for term in terms) + "}};"
        )
    # See generation_profiles.json's "_synth_override_comment": a
    # generator-family Auto match yields to the instrument default when the
    # prompt also asks for a playable instrument by name. This must resolve
    # IDENTICALLY to llm/generation_profiles.py's resolve() -- the combo box
    # this drives (PromptPanel::updateAutoFamilyLabel) is the user's live
    # preview of what Auto will actually pick.
    synth_override_terms = data.get("synth_override_terms", [])
    overridden_ids = [
        profile["id"] for profile in profiles
        if profile.get("overridden_by_synth_terms")
    ]
    lines.append(
        f"inline constexpr std::array<const char*, {len(synth_override_terms)}> "
        "terms_synth_override {{"
        + ", ".join(_cpp(term) for term in synth_override_terms) + "}};"
    )
    lines.extend([
        "",
        "inline const Profile* find(juce::String id)",
        "{",
        "    id = id.trim().toLowerCase();",
        "    for (const auto& profile : all)",
        "        if (id == profile.id) return &profile;",
        "    return nullptr;",
        "}",
        "",
        "template <size_t N>",
        "inline bool matchesAny(const juce::String& text, const std::array<const char*, N>& terms)",
        "{",
        "    for (const auto* term : terms)",
        "        if (text.contains(term)) return true;",
        "    return false;",
        "}",
        "",
        "inline const Profile& resolveAuto(const juce::String& prompt, bool synthHost)",
        "{",
        "    const auto text = prompt.toLowerCase();",
        "    if (synthHost)",
        "    {",
    ])
    # Every instrument family with auto_terms, in JSON order (the same order
    # llm/generation_profiles.py's resolve() iterates -- first match wins in
    # both). Any profile flagged overridden_by_synth_terms gets the extra
    # "and not a synth_override term" guard; every other check is a plain
    # matchesAny, exactly as before this fix.
    ordered_instrument_terms = [
        profile["id"] for profile in profiles
        if profile["kind"] == "instrument" and profile.get("auto_terms")
    ]
    for profile_id in ordered_instrument_terms:
        if profile_id in overridden_ids:
            lines.append(
                f"        if (matchesAny(text, terms_{profile_id}) "
                "&& ! matchesAny(text, terms_synth_override)) "
                f"return *find({_cpp(profile_id)});"
            )
        else:
            lines.append(
                f"        if (matchesAny(text, terms_{profile_id})) return *find({_cpp(profile_id)});"
            )
    lines.extend([
        f"        return *find({_cpp(data['defaults']['instrument'])});",
        "    }",
        "    if (matchesAny(text, terms_granular_effect)) return *find(\"granular_effect\");",
        f"    return *find({_cpp(data['defaults']['effect'])});",
        "}",
        "} // namespace GenerationProfiles",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        return 0 if TARGET.exists() and TARGET.read_text(encoding="utf-8") == expected else 1
    TARGET.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
