#!/usr/bin/env python3
"""
Generate the two consumers of Faust's voice-control label contract from the
one canonical source, llm/voice_contract.json.

Why this exists
----------------
FaustEngine::extractVoiceControls (host/Source/FaustEngine.cpp) matches Faust
parameter labels "gate", "freq"/"key" and "gain"/"vel"/"velocity" to bind the
three voice zones a generated instrument must declare.
llm/prompts/instrument_prompt.txt states the same three names to the model
that writes the Faust in the first place. Before this script, both were
hand-typed, independently, with nothing to notice if they drifted -- a rename
on either side produces an instrument that compiles cleanly and is silently
dead, because Faust itself has no idea those three names are special.

This is the same shape as tools/gen_stdlib_block.py, which this follows:
one canonical, human-edited source; the C++ and prompt consumers are both
MECHANICALLY derived from it, so they cannot say different things.

Division of responsibility
---------------------------
  CANONICAL (llm/voice_contract.json, human-edited) -- the zone list, the
      accepted label spelling(s) per zone IN MATCH ORDER, which spelling is
      PRIMARY (labels[0] -- the one the prompt teaches) vs an ALTERNATE
      FaustEngine still recognises but the prompt does not mention, and the
      Faust widget/default/range used to render the primary declaration.
  GENERATED (this script) -- host/Source/VoiceContract.generated.h (the C++
      match tables) and the GENERATED VOICE CONTRACT block spliced into
      llm/prompts/instrument_prompt.txt.

Usage
-----
    python tools/gen_voice_contract.py                # print both, to stdout
    python tools/gen_voice_contract.py --check         # exit 1 if either
                                                        # generated artifact is
                                                        # stale
    python tools/gen_voice_contract.py --write         # regenerate both
    python tools/gen_voice_contract.py --write-header  # regenerate only the
                                                        # C++ header
    python tools/gen_voice_contract.py --write-prompt  # regenerate only the
                                                        # prompt's spliced block

`--check` is what tools/check.sh's full level runs; it is how a hand-edit to
either generated file, or an edit to the canonical source that nobody
regenerated from, turns into a failing build instead of a silent drift back
into two hand-synced copies.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACT_FILE = ROOT / "llm" / "voice_contract.json"
HEADER_FILE = ROOT / "host" / "Source" / "VoiceContract.generated.h"
PROMPT_FILE = ROOT / "llm" / "prompts" / "instrument_prompt.txt"

HEADER_BEGIN = "// BEGIN GENERATED VOICE CONTRACT"
HEADER_END = "// END GENERATED VOICE CONTRACT"
PROMPT_BEGIN = "# BEGIN GENERATED VOICE CONTRACT"
PROMPT_END = "# END GENERATED VOICE CONTRACT"

# Cosmetic-only: the comment column each declaration's trailing `// ...` note
# starts at, in the ALREADY-hand-authored prompt text this replaces. Not part
# of the label contract itself -- purely reproducing the existing prompt
# byte-for-byte, which is what makes the splice provably a no-op on content.
# Recorded per Faust widget kind because the two present today (hslider,
# button) were not hand-aligned to the same column.
_COMMENT_COLUMN_BY_WIDGET = {"hslider": 49, "button": 50}


def load_contract() -> dict:
    return json.loads(CONTRACT_FILE.read_text())


def zone_names(contract: dict) -> list:
    return [z["zone"] for z in contract["zones"]]


# ── host/Source/VoiceContract.generated.h ───────────────────────────────────

def render_header(contract: dict) -> str:
    lines = [
        "#pragma once",
        HEADER_BEGIN,
        "// Generated by tools/gen_voice_contract.py from llm/voice_contract.json.",
        "// Do not hand-edit: run the script. This is the canonical source",
        "// FaustEngine::extractVoiceControls (FaustEngine.cpp) matches Faust",
        "// parameter labels against -- the only place in C++ the accepted",
        "// spellings are listed.",
        "",
        "namespace pf::VoiceContract",
        "{",
        "// A label FaustEngine recognises for a voice zone, and whether it carries",
        "// RAW MIDI units (key: the note number; vel/velocity: 0-127) rather than",
        "// the zone's default units (freq: Hz; gain: 0-1) -- see FaustEngine::noteOn",
        "// for the conversion this flag selects.",
        "struct Label { const char* name; bool rawUnits; };",
        "",
        "// Match order matters in every list below: first entry wins when a patch",
        "// declares more than one spelling for the same zone",
        "// (extractVoiceControls's \"first match wins per role\").",
        "",
    ]
    for zone in contract["zones"]:
        const_name = f"k{zone['zone'].capitalize()}Labels"
        lines.append(f"inline constexpr Label {const_name}[] = {{")
        for label in zone["labels"]:
            raw = "true" if label.get("rawUnits") else "false"
            lines.append(f'    {{ "{label["label"]}", {raw} }},')
        lines.append("};")
    lines.append("} // namespace pf::VoiceContract")
    lines.append(HEADER_END)
    return "\n".join(lines) + "\n"


# ── llm/prompts/instrument_prompt.txt ───────────────────────────────────────

def render_prompt_block(contract: dict) -> str:
    """The three declaration lines, byte-identical to the hand-authored text
    this replaces (see _COMMENT_COLUMN_BY_WIDGET).

    Ordered by contract["promptOrder"], NOT contract["zones"] -- the prompt's
    pedagogical order (pitch, level, gate) has never matched
    extractVoiceControls's match order (gate, freq, gain) and carries no
    match semantics of its own; see the note in llm/voice_contract.json.
    """
    zones_by_name = {z["zone"]: z for z in contract["zones"]}
    out = [PROMPT_BEGIN]
    for zone_name in contract["promptOrder"]:
        zone = zones_by_name[zone_name]
        primary = zone["labels"][0]["label"]
        widget = zone["widget"]
        if widget == "hslider":
            code = (f'  {zone["zone"]} = hslider("{primary}", {zone["default"]}, '
                    f'{zone["min"]}, {zone["max"]}, {zone["step"]});')
        elif widget == "button":
            code = f'  {zone["zone"]} = button("{primary}");'
        else:
            raise ValueError(f"unknown widget kind {widget!r} for zone {zone['zone']!r}")

        col = _COMMENT_COLUMN_BY_WIDGET[widget]
        out.append(code.ljust(col) + f'// {zone["comment"]}')
    out.append(PROMPT_END)
    return "\n".join(out)


def splice(text: str, block: str, begin: str, end: str, where: Path) -> str:
    start = text.find(begin)
    stop = text.find(end)
    if start == -1 or stop == -1:
        raise ValueError(
            f"markers not found in {where}. Expected {begin!r} and {end!r}."
        )
    return text[:start] + block + text[stop + len(end):]


def header_is_stale(contract: dict) -> bool:
    if not HEADER_FILE.exists():
        return True
    return HEADER_FILE.read_text() != render_header(contract)


def prompt_is_stale(contract: dict) -> bool:
    if not PROMPT_FILE.exists():
        return True
    text = PROMPT_FILE.read_text()
    if PROMPT_BEGIN not in text or PROMPT_END not in text:
        return True
    block = render_prompt_block(contract)
    spliced = splice(text, block, PROMPT_BEGIN, PROMPT_END, PROMPT_FILE)
    return spliced != text


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if the header or the prompt's spliced "
                             "block is out of date with llm/voice_contract.json.")
    parser.add_argument("--write", action="store_true",
                        help="Regenerate both the header and the prompt block.")
    parser.add_argument("--write-header", action="store_true",
                        help="Regenerate only host/Source/VoiceContract.generated.h.")
    parser.add_argument("--write-prompt", action="store_true",
                        help="Regenerate only the spliced block in "
                             "llm/prompts/instrument_prompt.txt.")
    args = parser.parse_args(argv)

    contract = load_contract()

    if args.check:
        stale = []
        if header_is_stale(contract):
            stale.append(str(HEADER_FILE.relative_to(ROOT)))
        if prompt_is_stale(contract):
            stale.append(str(PROMPT_FILE.relative_to(ROOT)))
        if stale:
            print("VOICE CONTRACT ARTIFACTS ARE STALE against "
                  f"{CONTRACT_FILE.relative_to(ROOT)}:", file=sys.stderr)
            for s in stale:
                print(f"  STALE  {s}", file=sys.stderr)
            print("\nRun: python tools/gen_voice_contract.py --write", file=sys.stderr)
            return 1
        print(f"OK -- {HEADER_FILE.relative_to(ROOT)} and "
              f"{PROMPT_FILE.relative_to(ROOT)}'s generated block both match "
              f"{CONTRACT_FILE.relative_to(ROOT)}")
        return 0

    if args.write or args.write_header:
        HEADER_FILE.write_text(render_header(contract))
        print(f"Wrote {HEADER_FILE.relative_to(ROOT)}", file=sys.stderr)

    if args.write or args.write_prompt:
        text = PROMPT_FILE.read_text()
        block = render_prompt_block(contract)
        PROMPT_FILE.write_text(splice(text, block, PROMPT_BEGIN, PROMPT_END, PROMPT_FILE))
        print(f"Wrote generated block into {PROMPT_FILE.relative_to(ROOT)}", file=sys.stderr)

    if not (args.write or args.write_header or args.write_prompt):
        print(render_header(contract))
        print(render_prompt_block(contract))

    return 0


if __name__ == "__main__":
    sys.exit(main())
