#!/usr/bin/env python3
"""
Generate llm/prompts/system_prompt_presentation.txt (the effects prompt plus
the control-presentation instructions) from two canonical sources.

Why this exists
----------------
bench/presentation_baseline.json (Brief A's 19-entry corpus) measured the
production prompt at a mean of 1.74/8 presentation affordances, with six of
eight -- hgroup, nested grouping, any non-hslider widget, checkbox/button,
[style:knob], [scale:log]/[scale:exp] -- at exactly 0/19 (see
OPEN_QUESTIONS.md's "near-0/8" finding). llm/presentation_block.txt is the
prompt-side experiment addressing that: instructions telling the model to
group controls, choose widgets deliberately, and taper Hz/time parameters
logarithmically. This is an ACTIVE, CHANGING experiment artifact, not a
settled decision -- it belongs in the prompt path (this script's generated
consumer), not in docs/, which holds decisions already made.

This follows the same shape as tools/gen_voice_contract.py: one canonical,
human-edited source generates a consumer, with `--check` as the staleness
gate so a hand-edit to the generated file or a forgotten regenerate after
editing the canonical source turns into a failing check, not a silent split.

Why the canonical source is llm/presentation_block.txt and not
llm/prompts/presentation_block.txt
--------------------------------------------------------------------------
`.claude/hooks/check_prompt_invariants.py:58` guards every file matching
`llm/prompts/[A-Za-z0-9_-]+\\.txt$`: it BLOCKS a Write/Edit unless the file
contains the ADR-009 duplicate-symbol sentence, a "process ... exactly once"
clause, and intact `# BEGIN/END GENERATED STDLIB REFERENCE` markers
(check_prompt_invariants.py:200-227) -- deliberately generalised from one
filename to the whole directory (its own docstring, lines 1-13) so no file
placed there can go unguarded. presentation_block.txt is a bare fragment; it
has none of those three things and would fail closed on the first write. The
canonical source therefore lives at the top of llm/, one level up, where the
hook's regex does not reach. The GENERATED file, system_prompt_presentation.txt,
lives where the user asked (llm/prompts/) and passes the hook cleanly because
it is base + block: system_prompt.txt already carries the ADR-009 sentence,
the process-once clause and the stdlib markers, and the appended block
introduces no fabricated ns.func token and no foreign-language construct.

Division of responsibility
---------------------------
  CANONICAL (llm/presentation_block.txt, human-edited) -- the grouping,
      widget-selection, scale and syntax rules.
  BASE (llm/prompts/system_prompt.txt, itself canonical/generated for its
      own stdlib block, unmodified by this script)
  GENERATED (this script) -- llm/prompts/system_prompt_presentation.txt,
      the concatenation of the two, byte-derived so it cannot say something
      different from either source.

Usage
-----
    python tools/gen_presentation_prompt.py            # print to stdout
    python tools/gen_presentation_prompt.py --check     # exit 1 if stale
    python tools/gen_presentation_prompt.py --write     # regenerate

Wired into tools/check.sh's `full` level as a staleness gate, same shape as
the voice-contract check beside it. It asserts the generated file has not
drifted from its two sources; it says nothing about generation QUALITY --
that is bench/presentation_checker.py against bench/presentation_baseline.json,
run by hand.
"""
import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CANONICAL_FILE = ROOT / "llm" / "presentation_block.txt"
BASE_FILE = ROOT / "llm" / "prompts" / "system_prompt.txt"
GENERATED_FILE = ROOT / "llm" / "prompts" / "system_prompt_presentation.txt"

PROVENANCE = (
    "# GENERATED by tools/gen_presentation_prompt.py from\n"
    "# llm/prompts/system_prompt.txt + llm/presentation_block.txt.\n"
    "# Do not hand-edit: edit the canonical block, then rerun the script.\n"
)

# Where the block is inserted: BEFORE this marker, not appended at EOF.
#
# tests/test_prompt_stdlib.py's iter_prompt_examples() extracts each few-shot
# example by splitting on "\nFAUST:\n" / "\nUSER:", and the LAST example in the
# file has no following "\nUSER:" to stop at -- it runs to EOF, on the
# (previously unstated but load-bearing) assumption that nothing follows the
# last example. A naive append-at-EOF puts this block's prose inside that
# extraction, which corrupted the chorus example ("syntax error, unexpected
# IDENT") and failed test_every_few_shot_example_compiles the first time this
# script was written that way. Splicing before EXAMPLES: keeps every example
# properly bounded, same as it is in the unmodified base prompt.
EXAMPLES_MARKER = "\nEXAMPLES:\n"


def render() -> str:
    base = BASE_FILE.read_text()
    block = CANONICAL_FILE.read_text()
    if not base.endswith("\n"):
        base += "\n"
    if EXAMPLES_MARKER not in base:
        raise ValueError(
            f"{BASE_FILE.relative_to(ROOT)} has no {EXAMPLES_MARKER!r} marker "
            "to splice the presentation block before."
        )
    before, _, after = base.partition(EXAMPLES_MARKER)
    spliced = before + "\n" + block + EXAMPLES_MARKER.lstrip("\n") + after
    return PROVENANCE + "\n" + spliced


def is_stale() -> bool:
    if not GENERATED_FILE.exists():
        return True
    return GENERATED_FILE.read_text() != render()


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if system_prompt_presentation.txt is "
                             "stale against its two sources.")
    parser.add_argument("--write", action="store_true",
                        help="Regenerate llm/prompts/system_prompt_presentation.txt.")
    args = parser.parse_args(argv)

    if args.check:
        if is_stale():
            print(
                "PRESENTATION PROMPT IS STALE against "
                f"{CANONICAL_FILE.relative_to(ROOT)} and "
                f"{BASE_FILE.relative_to(ROOT)}:\n"
                f"  STALE  {GENERATED_FILE.relative_to(ROOT)}\n\n"
                "Run: python tools/gen_presentation_prompt.py --write",
                file=sys.stderr,
            )
            return 1
        print(f"OK -- {GENERATED_FILE.relative_to(ROOT)} matches its sources")
        return 0

    if args.write:
        GENERATED_FILE.write_text(render())
        print(f"Wrote {GENERATED_FILE.relative_to(ROOT)}", file=sys.stderr)
        return 0

    print(render())
    return 0


if __name__ == "__main__":
    sys.exit(main())
